name: Service CI

on:
  push:
   branches:
     - main
   paths:
     - status-updater/**/*
     - .github/workflows/service-cd.yml

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: Restore Packages
        run: dotnet restore
        working-directory: ./status-updater
      - name: Publish
        run: dotnet publish -p:PublishProfile=Win-x64
        working-directory: ./status-updater
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: service
          path: status-updater/bin/Release/net5.0/publish
