name: Service CI

on: [push]

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: Build
        run: dotnet build
        working-directory: ./status-updater
